CRM/urls.py
from django.contrib import admin
from django.urls import path, re_path
from app01 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # 登陆
    path('login/', views.Login.as_view(), name = "login"),
    path('logout/', views.Logout.as_view(), name = "logout"),

    # 验证码
    path('get_validcode/', views.get_validcode, name = "validcode"),
    # 注册
    path('reg/', views.Reg.as_view()),
    #*****************************************************
    path('index/', views.index, name = "index"),


    path('mycustomers/', views.CustomerView.as_view(), name = 'mycustomers'),
    path('customers/', views.CustomerView.as_view(), name = 'customers'),
    # 批量处理部分
    path('patch_action/',views.CustomerView.as_view(), name = 'patch_action'),

    path('add_customer/', views.AddEditCustomer.as_view(), name='add_customer'),
    re_path('edit_customer/(\d+)', views.AddEditCustomer.as_view(), name='edit_customer'),
    re_path('del_customer/(\d+)', views.AddEditCustomer.as_view(), name='del_customer'),

    # 跟进记录
    path('consult_records/', views.ConsultRecordView.as_view(),name="consult_records"),

    path('consult_add/', views.AddConsultRecordView.as_view(),name="consult_add"),

]

app01/models.py
from django.contrib.auth.models import AbstractUser


from django.contrib.auth.models import AbstractUser
from django.db import models

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, User
from multiselectfield import MultiSelectField
from django.utils.safestring import mark_safe

course_choices = (('LinuxL', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),)

class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)

source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)

enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))

seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)
pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    ('refund', "退款"),)

attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)




class UserInfo(AbstractUser):
    tel=models.CharField(max_length=32,null=True,blank=True)
    gender=models.IntegerField(choices=((1,"男"),(2,"女")),default=1)
    def __str__(self):
        return self.username




class Customer(models.Model):
    """
    客户表
    """
    qq = models.CharField('QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
    name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名')
    sex_type = (('male', '男'), ('female', '女'))
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True, null=True)
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)
    phone = models.BigIntegerField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')
    introduce_from = models.ForeignKey('Customer', verbose_name="转介绍自学员", blank=True, null=True,on_delete=models.CASCADE)
    course = MultiSelectField("咨询课程", choices=course_choices)
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField("客户备注", blank=True, null=True, )
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",
                              help_text="选择客户此时的状态")
    date = models.DateTimeField("咨询日期", auto_now_add=True)
    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True)
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True)
    consultant = models.ForeignKey('UserInfo', verbose_name="销售", related_name='customers', blank=True, null=True,on_delete=models.CASCADE )
    class_list = models.ManyToManyField('ClassList', verbose_name="已报班级", )


    def __str__(self):
        return self.name



    def get_classlist(self):
        l=[]
        for cls in self.class_list.all():
            l.append(str(cls))
        return mark_safe(",".join(l))

class Campuses(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    def __str__(self):
        return self.name

class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期")
    campuses = models.ForeignKey('Campuses', verbose_name="校区",on_delete=models.CASCADE)
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True)
    #contract = models.ForeignKey('ContractTemplate', verbose_name="选择合同模版", blank=True, null=True,on_delete=models.CASCADE)
    teachers = models.ManyToManyField('UserInfo', verbose_name="老师")
    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班额及类型', blank=True,
                                  null=True)

    class Meta:
        unique_together = ("course", "semester", 'campuses')

    def __str__(self):
        return "{}{}({})".format(self.get_course_display(), self.semester, self.campuses)

class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="所咨询客户", on_delete=models.CASCADE)
    note = models.TextField(verbose_name="跟进内容...")
    status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")
    consultant = models.ForeignKey("UserInfo", verbose_name="跟进人", related_name='records', on_delete=models.CASCADE)
    date = models.DateTimeField("跟进日期", auto_now_add=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)

    def __str__(self):
        return str(self.customer)

#############################################################

# class ContractTemplate(models.Model):
#     """
#     合同模板表
#     """
#     name = models.CharField("合同名称", max_length=128, unique=True)
#     content = models.TextField("合同内容")
#     date = models.DateField(auto_now=True)
#
#
# class ConsultRecord(models.Model):
#     """
#     跟进记录表
#     """
#     customer = models.ForeignKey('Customer', verbose_name="所咨询客户")
#     note = models.TextField(verbose_name="跟进内容...")
#     status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")
#     consultant = models.ForeignKey("UserProfile", verbose_name="跟进人", related_name='records')
#     date = models.DateTimeField("跟进日期", auto_now_add=True)
#     delete_status = models.BooleanField(verbose_name='删除状态', default=False)
#
#
# class Enrollment(models.Model):
#     """
#     报名表
#     """
#
#     why_us = models.TextField("为什么报名", max_length=1024, default=None, blank=True, null=True)
#     your_expectation = models.TextField("学完想达到的具体期望", max_length=1024, blank=True, null=True)
#     contract_agreed = models.BooleanField("我已认真阅读完培训协议并同意全部协议内容", default=False)
#     contract_approved = models.BooleanField("审批通过", help_text="在审阅完学员的资料无误后勾选此项,合同即生效", default=False)
#     enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name="报名日期")
#     memo = models.TextField('备注', blank=True, null=True)
#     delete_status = models.BooleanField(verbose_name='删除状态', default=False)
#     customer = models.ForeignKey('Customer', verbose_name='客户名称')
#     school = models.ForeignKey('Campuses')
#     enrolment_class = models.ForeignKey("ClassList", verbose_name="所报班级")
#
#     class Meta:
#         unique_together = ('enrolment_class', 'customer')
#
#
# class PaymentRecord(models.Model):
#     """
#     缴费记录表
#     """
#     pay_type = models.CharField("费用类型", choices=pay_type_choices, max_length=64, default="deposit")
#     paid_fee = models.IntegerField("费用数额", default=0)
#     note = models.TextField("备注", blank=True, null=True)
#     date = models.DateTimeField("交款日期", auto_now_add=True)
#     course = models.CharField("课程名", choices=course_choices, max_length=64, blank=True, null=True, default='N/A')
#     class_type = models.CharField("班级类型", choices=class_type_choices, max_length=64, blank=True, null=True,
#                                   default='N/A')
#     enrolment_class = models.ForeignKey('ClassList', verbose_name='所报班级', blank=True, null=True)
#     customer = models.ForeignKey('Customer', verbose_name="客户")
#     consultant = models.ForeignKey('UserProfile', verbose_name="销售")
#     delete_status = models.BooleanField(verbose_name='删除状态', default=False)
#
#     status_choices = (
#         (1, '未审核'),
#         (2, '已审核'),
#     )
#     status = models.IntegerField(verbose_name='审核', default=1, choices=status_choices)
#
#     confirm_date = models.DateTimeField(verbose_name="确认日期", null=True, blank=True)
#     confirm_user = models.ForeignKey(verbose_name="确认人", to='UserProfile', related_name='confirms', null=True,
#                                      blank=True)
#
#
# class CourseRecord(models.Model):
#     """课程记录表"""
#     day_num = models.IntegerField("节次", help_text="此处填写第几节课或第几天课程...,必须为数字")
#     date = models.DateField(auto_now_add=True, verbose_name="上课日期")
#     course_title = models.CharField('本节课程标题', max_length=64, blank=True, null=True)
#     course_memo = models.TextField('本节课程内容', max_length=300, blank=True, null=True)
#     has_homework = models.BooleanField(default=True, verbose_name="本节有作业")
#     homework_title = models.CharField('本节作业标题', max_length=64, blank=True, null=True)
#     homework_memo = models.TextField('作业描述', max_length=500, blank=True, null=True)
#     scoring_point = models.TextField('得分点', max_length=300, blank=True, null=True)
#     re_class = models.ForeignKey('ClassList', verbose_name="班级")
#     teacher = models.ForeignKey('UserProfile', verbose_name="讲师")
#
#     class Meta:

app01/forms.py
from django import forms
from app01.models import UserInfo, Customer, ConsultRecord
from django.contrib import auth
from django.core.exceptions import ValidationError
from django.forms import widgets
from multiselectfield.forms.fields import MultiSelectFormField
from django.conf import settings

class UserInfoForm(forms.Form):

    username = forms.CharField(min_length=5, label="用户名", error_messages={'required':'不能为空'})
    password = forms.CharField(min_length=8, label="密码", widget=widgets.PasswordInput())
    r_password = forms.CharField(min_length=8, label="确认密码", widget=widgets.PasswordInput())
    email = forms.EmailField(label="邮箱")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for filed in self.fields.values():
            filed.widget.attrs.update({'class': 'form-control'})


    def clean_username(self):
        val = self.cleaned_data.get('username')
        user = UserInfo.objects.filter(username = val).first()
        if user:
        #用户名重复
            raise ValidationError('用户已经存在！')
        else:
            return val

    def clean_password(self):
        val = self.cleaned_data.get('password')
        if val.isdigit():
            # 是纯数字
            raise ValidationError('密码不能使纯数字！')
        else:
            return val

    def clean_email(self):
        val = self.cleaned_data.get('email')
        if val.endswith('163.com'):
            return val
        else:
            raise ValidationError('必须是163邮箱！')

    def clean(self):
        password = self.cleaned_data.get('password')
        r_password = self.cleaned_data.get('r_password')

        if password and r_password and password != r_password:
            self.add_error("r_password", ValidationError("两次密码不一致！"))
            # raise ValidationError('两次密码不一致')
        else:
            return self.cleaned_data



class CustomerModerForm(forms.ModelForm):

    class Meta:
        model = Customer
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields.values():

            if not isinstance(field, MultiSelectFormField):
                field.widget.attrs.update({'class': 'form-control'})




class ConsultRecordModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        user_obj = UserInfo.objects.get(pk = settings.CURRENT_USER_PK)
        self.fields["consultant"].widget.choices = [(user_obj.pk, user_obj.username)]

        user_customers = Customer.objects.filter(consultant=user_obj)
        customers = []
        for item in user_customers:
            each = (item.pk, item.name)
            customers.append(each)

        self.fields["customer"].widget.choices = customers

        for field in self.fields.values():

            if not isinstance(field, MultiSelectFormField):
                field.widget.attrs.update({'class': 'form-control'})
    class Meta:
        model = ConsultRecord
        # fields="__all__"
        exclude = ["delete_status"]

templates/add_consult.html
{% extends 'starter.html' %}


{% block content %}


    <section class="content-header">
        <h1>添加跟进记录</h1>
    </section>
    <div class="content-wrapper">

        <section class="content">

            <div class="row">
                <div class="col-md-8">
                    <form action="" method="post" novalidate>
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <label for="">{{ field.label }}</label>
                                {{ field }}
                                <span class="error">{{ field.errors.0 }}</span>
                            </div>
                        {% endfor %}
                        <button class="btn btn-default">提交</button>
                    </form>
                </div>
            </div>

        </section>
        <!-- /.content -->
    </div>


{% endblock %}

templates/add_customer.html
{% extends 'starter.html' %}


{% block content %}

    <section class="content-header">
        <h1>添加客户</h1>
    </section>
    <div class="content-wrapper">

        <section class="content">

            <div class="row">
                <div class="col-md-8">
                    <form action="" method="post" novalidate>
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <label for="">{{ field.label }}</label>
                                {{ field }}
                                <span class="error">{{ field.errors.0 }}</span>
                            </div>
                        {% endfor %}
                        <button class="btn btn-default">提交</button>
                    </form>
                </div>
            </div>

        </section>
        <!-- /.content -->
    </div>



{% endblock %}

templates/consultrecord.html
{% extends "starter.html" %}



{% block content %}
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>跟进记录</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item">
                            <a class="btn btn-primary" id="add-btn" href="{% url 'consult_add' %}">添加跟进记录</a>
                        </li>

                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">


                        <div class="card-body text-center" id='pagination_father'>

                            <table id="example2" class="table table-bordered table-hover">
                                <thead>
                                <tr>

                                    <th>编号</th>
                                    <th>咨询客户</th>
                                    <th>跟进内容</th>
                                    <th>跟进状态</th>
                                    <th>跟进人</th>
                                    <th>操作</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for consult_record in consult_record_list %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ consult_record.customer.name }}</td>
                                        <td>{{ consult_record.note }}</td>
                                        <td>{{ consult_record.customer.get_status_display }}</td>
                                        <td>{{ consult_record.consultant|default:"暂无" }}</td>
                                        <td>
                                            <a href="" class="btn btn-warning btn-sm">编辑</a>
                                            <a href="" class="btn btn-danger btn-sm">删除</a>
                                        </td>

                                    </tr>
                                {% endfor %}


                                </tbody>


                            </table>

                            <ul class="pagination">
                                {{ pagination.page_html|safe }}
                            </ul>
                        </div>


                    </div>
                    <!-- /.card-header -->


                </div>


            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>

{% endblock %}

templates/customers.html
{% extends 'starter.html' %}

{% block content %}
    <style>

        .pagination li {
            width: 60px;
            border: 0.5px solid #9f9f9f;
            right: 0;

        }

        .active {
            background-color: #0e84b5;
        }

        .pagination li a {
            color: #000;
            font-size: 16px;
        }

        #pagination_father {
            position: relative;
            padding-bottom: 50px !important;
        }

        .pagination {
            position: absolute;
            text-align: center;
            right: 0;
            margin-top: 10px;

        }
        .search_form{
            position: absolute;
            right: 0;
        }

        .edit-btn{
            cursor: pointer;
        }

        .unregistered{
            background-color: red;
        }

        .studying{
            background-color: green;
        }

        .signed{
            background-color: yellow;
        }

        .paid_in_full{
            background-color: blue;
        }


    </style>

    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{ label }}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item">
                            <a class="btn btn-primary" id="add-btn" href="{% url 'add_customer' %}">添加客户</a>
                        </li>

                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">

                        <!-- 模糊查询的form表单  -->
                        <form action="" method="get" class="pull-right search_form">

                                <select name="field" id="s1" class="form-control"
                                        style="display: inline-block;width: 100px">
                                    <option value="name">姓名</option>
                                    <option value="qq">qq</option>
                                    <option value="phone">手机</option>
                                    <option value="status">状态</option>
                                </select>
                                <input class="form-control" style="display: inline-block;width: 200px" type="text"
                                       name="value">
                                <button style="vertical-align: 0px" class="btn btn-success">search</button>

                        </form>



                        {# 批量处理#}
                        <form action="{% url 'patch_action' %}" method="post">
                            {% csrf_token %}

                            <select name="action" id="" class="form-control" style="display: inline-block;width: 240px">
                                <option value="patch_delete">请选择批量处理方法</option>
                                <option value="patch_delete">删除客户</option>
                                <option value="patch_reverse_public">公户转私户</option>
                                <option value="patch_reverse_private">私户转公户</option>

                            </select>

                            <button style="vertical-align: 0px" class="btn btn-danger" id="operation_btn">go</button>


                            <div class="card-body text-center" id='pagination_father'>

                                <table id="example2" class="table table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th><input type="checkbox"></th>
                                        <th>编号</th>
                                        <th>客户姓名</th>
                                        <th>性别</th>
                                        <th>QQ</th>
                                        <th>手机号</th>
                                        <th>客户来源</th>
                                        <th>咨询日期</th>
                                        <th>当前状态</th>
                                        <th>销售</th>
                                        <th>所报班级</th>
                                        <th>跟进记录</th>
                                        <th>操作</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for customer in customer_list %}
                                        <tr>
                                            <td><input type="checkbox" name="selected_pk_list"
                                                       value="{{ customer.pk }}"></td>
                                            <td>{{ forloop.counter|add:current_page_numbering }}</td>
                                            <td>{{ customer.name }}</td>
                                            <td>{{ customer.get_sex_display }}</td>
                                            <td>{{ customer.qq }}</td>
                                            <td>{{ customer.phone }}</td>
                                            <td>{{ customer.get_source_display }}</td>
                                            <td>{{ customer.date|date:'Y-m-d' }}</td>
                                            <td class="{{customer.status}}">{{ customer.get_status_display }}</td>
                                            <td>{{ customer.consultant }}</td>
                                            <td>{{ customer.get_classlist }}</td>
                                            <td><a href="{% url 'consult_records' %}?customer_id={{ customer.pk }}">跟进记录</a></td>
                                            <td>
                                                <a class="btn-sm btn-warning edit-btn" href="{% url 'edit_customer' customer.pk %}">编辑</a>
                                                <a class="btn-sm btn-danger danger-btn" href="{% url 'del_customer' customer.pk %}">删除</a>
                                            </td>
                                        </tr>
                                    {% endfor %}


                                    </tbody>


                                </table>

                                <ul class="pagination">
                                    {{ pagination.page_html|safe }}
                                </ul>
                            </div>

                        </form>


                    </div>
                    <!-- /.card-header -->


                </div>


            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>

{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
</head>
<body>

    {% csrf_token %}

    <div class="container">
        <h4>登陆页面</h4>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">

                {# 账号输入框#}
                <div class="form-group">
                    <label for="">账号</label>
                    <input type="text" class="form-control" id="user">
                </div>

                {# 密码输入框#}
                <div class="form-group">
                    <label for="">密码</label>
                    <input type="text" class="form-control" id="pwd">
                </div>

                {#验证码输入框#}
                <div class="form-group">
                    <label for="">验证码</label>
                    <div class="row">
                        <div class="col-md-6">
                            <input type="text" class="form-control" id="validcode">
                        </div>

                        <div class="col-md-6">
                            <img src="{% url 'validcode' %}" alt="" id="validcode_img">
                        </div>
                    </div>

                    <span class="error"></span>

                </div>

                <input type="button" class="btn btn-primary pull-right login_btn" value="提交">

            </div>


        </div>
    </div>


    <script src="/static/js/jquery.js"></script>
    <script>
        $('.login_btn').click(function () {

            $.ajax({
                url:'',
                type:'post',
                data:{
                    user : $('#user').val(),
                    pwd : $('#pwd').val(),
                    validcode : $('#validcode').val(),
                    csrfmiddlewaretoken: $("[name = 'csrfmiddlewaretoken']").val()

                },
                success:function (response) {

                    if (response.error_msg){
                        $('.error').html(response.error_msg).css({'color' : 'red'})

                    }else{
                        location.href = '/index/'
                    }


                }
            })


        });


        {#对验证码图片进行涮新，img标签的src加？就可以重新发送请求#}
        $('#validcode_img').click(function () {

            this.src += "?";

        });
    </script>

</body>
</html>

templates/menu.html
<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
        data-accordion="false">

        {% for menu in menus.values %}
            <li class="nav-item has-treeview  {{ menu.pclass }}">

            {#     父级标签       #}
            <a href="" class="nav-link active">
                <i class="nav-icon fas fa-tachometer-alt"></i>
                <p>
                    {{menu.title}}
                    <i class="right fas fa-angle-left"></i>
                </p>
            </a>


            <ul class="nav nav-treeview">
                {% for child in menu.children %}

                    <li class="nav-item">
                    <a href="{{ child.curl }}" class="nav-link {{ child.class }}">
                        <i class="far fa-circle nav-icon"></i>
                        <p>{{ child.ctitle }}</p>
                    </a>
                </li>

                {% endfor %}

            </ul>
        </li>
        {% endfor %}




    </ul>
</nav>

templates/reg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
</head>
<body>

    {% csrf_token %}

    <div class="container">
        <h4>注册页面</h4>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">

                {% for field in forms %}

                    <div class="form-group">
                        <label for="">{{field.label}}</label>
                        {{field}}
                        {# 真实错误信息#}
                        <span class="error"></span>
                    </div>


                {% endfor %}


                <input type="button" class="btn btn-primary pull-right" id="reg_btn" value="提交">

            </div>


        </div>
    </div>


    <script src="/static/js/jquery.js"></script>
    <script>

        $('#reg_btn').click(function () {

            $.ajax({
                url : "",
                type : "post",
                data : {
                    username : $('#id_username').val(),
                    password :  $('#id_password').val(),
                    r_password : $('#id_r_password').val(),
                    email : $('#id_email').val(),
                    csrfmiddlewaretoken : $("[name = 'csrfmiddlewaretoken']").val()

                },
                success : function (response) {

                    console.log(response);
                    console.log(typeof response);

                    if(response.user){
                        {# 注册成功成功#}
                        location.href = "/login/";
                    }else {





                        // 清除错误
                        $(".error").html("");
                        $(".form-group").removeClass("has-error");
                        $.each(response.error_msg, function (index, ele) {

                            $('#id_' + index).next().html(ele[0]).css('color', 'red').parent().addClass('has-error')

                        });
                    }
                }
            });


        });


    </script>

</body>
</html>